// <auto-generated />
using System;
using EFCore;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EFCore.Migrations
{
    [DbContext(typeof(WebshopDbContext))]
    [Migration("20260403100629_Initial migration")]
    partial class Initialmigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("Finnish_Swedish_CI_AS")
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Entities.Address", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("StreetAddress")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("Id");

                    b.ToTable("Addresses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            City = "Uddevalla",
                            Country = "Sweden",
                            StreetAddress = "Uddevallagatan 1"
                        });
                });

            modelBuilder.Entity("Entities.AddressCustomer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AddressId")
                        .HasColumnType("int");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AddressId");

                    b.HasIndex("CustomerId");

                    b.ToTable("AddressCustomers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AddressId = 1,
                            CustomerId = 1
                        });
                });

            modelBuilder.Entity("Entities.Brand", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("Id");

                    b.ToTable("Brands");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Levi´s"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Weekday"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Nike"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Tommy Hilfiger"
                        });
                });

            modelBuilder.Entity("Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Pants"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Shirt"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Jacket"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Shoes"
                        });
                });

            modelBuilder.Entity("Entities.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("Date");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("Id");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BirthDate = new DateTime(1998, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "erik.eriksson@gmail.se",
                            Name = "Erik Eriksson",
                            Phone = "0705679901"
                        });
                });

            modelBuilder.Entity("Entities.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<string>("OrderNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("PaymentId")
                        .HasColumnType("int");

                    b.Property<int>("ShippingId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("PaymentId");

                    b.HasIndex("ShippingId");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CustomerId = 1,
                            OrderNumber = "1001050608",
                            PaymentId = 1,
                            ShippingId = 1
                        },
                        new
                        {
                            Id = 2,
                            CustomerId = 1,
                            OrderNumber = "1001050609",
                            PaymentId = 2,
                            ShippingId = 2
                        },
                        new
                        {
                            Id = 3,
                            CustomerId = 1,
                            OrderNumber = "1001070819",
                            PaymentId = 2,
                            ShippingId = 1
                        },
                        new
                        {
                            Id = 4,
                            CustomerId = 1,
                            OrderNumber = "1001037849",
                            PaymentId = 3,
                            ShippingId = 2
                        });
                });

            modelBuilder.Entity("Entities.OrderProduct", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("ProductAmount")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderProducts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            OrderId = 1,
                            ProductAmount = 2,
                            ProductId = 1
                        },
                        new
                        {
                            Id = 2,
                            OrderId = 2,
                            ProductAmount = 1,
                            ProductId = 5
                        },
                        new
                        {
                            Id = 3,
                            OrderId = 3,
                            ProductAmount = 1,
                            ProductId = 10
                        },
                        new
                        {
                            Id = 4,
                            OrderId = 4,
                            ProductAmount = 3,
                            ProductId = 11
                        });
                });

            modelBuilder.Entity("Entities.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Payments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Type = 0
                        },
                        new
                        {
                            Id = 2,
                            Type = 1
                        },
                        new
                        {
                            Id = 3,
                            Type = 2
                        });
                });

            modelBuilder.Entity("Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BrandId")
                        .HasColumnType("int");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("LongDescription")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<bool>("OnSale")
                        .HasColumnType("bit");

                    b.Property<decimal>("Price")
                        .HasColumnType("Money");

                    b.Property<string>("ShortDescription")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("BrandId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BrandId = 1,
                            CategoryId = 1,
                            LongDescription = "Made from 98% cotton and 2% elastane. Machine wash at 30°C, do not tumble dry. Iron inside out on low heat. Not water resistant.",
                            Name = "White Slim Fit Jeans",
                            OnSale = false,
                            Price = 60m,
                            ShortDescription = "Clean and crisp white jeans for any casual occasion."
                        },
                        new
                        {
                            Id = 2,
                            BrandId = 2,
                            CategoryId = 1,
                            LongDescription = "Crafted from 100% premium cotton. Dry clean recommended. Iron on medium heat. Tailored fit with a straight leg cut.",
                            Name = "Black Suit Trousers in Cotton",
                            OnSale = false,
                            Price = 80m,
                            ShortDescription = "Elegant black trousers perfect for the office or a night out."
                        },
                        new
                        {
                            Id = 3,
                            BrandId = 2,
                            CategoryId = 1,
                            LongDescription = "Made from soft cotton blend. Machine wash at 40°C. Tumble dry on low. Iron on medium heat. Versatile enough for both casual and smart casual looks.",
                            Name = "Grey Relaxed Chinos",
                            OnSale = false,
                            Price = 55m,
                            ShortDescription = "Comfortable everyday chinos with a modern relaxed fit."
                        },
                        new
                        {
                            Id = 4,
                            BrandId = 1,
                            CategoryId = 1,
                            LongDescription = "Made from durable ripstop fabric, 100% cotton. Machine wash at 30°C. Do not tumble dry. Water resistant coating on the outer layer.",
                            Name = "Navy Blue Cargo Pants",
                            OnSale = false,
                            Price = 60m,
                            ShortDescription = "Functional cargo pants with plenty of pocket space."
                        },
                        new
                        {
                            Id = 5,
                            BrandId = 1,
                            CategoryId = 1,
                            LongDescription = "95% cotton, 5% elastane. Machine wash at 30°C inside out to preserve color. Do not bleach. Iron on low heat.",
                            Name = "Dark Wash Straight Leg Jeans",
                            OnSale = true,
                            Price = 70m,
                            ShortDescription = "A timeless dark wash jean that goes with everything."
                        },
                        new
                        {
                            Id = 6,
                            BrandId = 4,
                            CategoryId = 2,
                            LongDescription = "100% cotton Oxford weave. Machine wash at 40°C. Iron on medium to high heat while slightly damp for best results. Not water resistant.",
                            Name = "White Oxford Button-Down Shirt",
                            OnSale = false,
                            Price = 45m,
                            ShortDescription = "A classic white Oxford shirt for a clean everyday look."
                        },
                        new
                        {
                            Id = 7,
                            BrandId = 4,
                            CategoryId = 2,
                            LongDescription = "Made from 100% cotton. Machine wash at 30°C. Iron on medium heat. Slim fit cut designed to be tucked in.",
                            Name = "Slim Fit Striped Dress Shirt",
                            OnSale = false,
                            Price = 50m,
                            ShortDescription = "Sharp striped dress shirt for a polished office look."
                        },
                        new
                        {
                            Id = 8,
                            BrandId = 2,
                            CategoryId = 2,
                            LongDescription = "100% brushed cotton flannel. Machine wash at 40°C. Tumble dry on low. Iron on medium heat. Can be worn open as a light jacket.",
                            Name = "Oversized Flannel Shirt",
                            OnSale = false,
                            Price = 40m,
                            ShortDescription = "Cozy flannel shirt perfect for layering on cooler days."
                        },
                        new
                        {
                            Id = 9,
                            BrandId = 2,
                            CategoryId = 2,
                            LongDescription = "55% linen, 45% cotton. Machine wash at 30°C or hand wash. Do not tumble dry. Iron on medium heat while damp. Lightweight and breathable.",
                            Name = "Black Linen Shirt",
                            OnSale = false,
                            Price = 45m,
                            ShortDescription = "Breathable linen shirt ideal for warm weather."
                        },
                        new
                        {
                            Id = 10,
                            BrandId = 1,
                            CategoryId = 2,
                            LongDescription = "100% cotton denim. Machine wash at 30°C inside out to preserve color. Do not bleach. Iron on medium heat.",
                            Name = "Denim Shirt Regular Fit",
                            OnSale = true,
                            Price = 47m,
                            ShortDescription = "Versatile denim shirt that works as a shirt or light jacket."
                        },
                        new
                        {
                            Id = 11,
                            BrandId = 3,
                            CategoryId = 3,
                            LongDescription = "Shell: 100% polyester. Filling: 80% down, 20% feather. Machine wash at 30°C on gentle cycle. Water resistant outer shell. Suitable for temperatures down to -10°C.",
                            Name = "Black Puffer Jacket",
                            OnSale = false,
                            Price = 13m,
                            ShortDescription = "Warm and lightweight puffer jacket for cold days."
                        },
                        new
                        {
                            Id = 12,
                            BrandId = 2,
                            CategoryId = 3,
                            LongDescription = "100% nylon shell with polyester lining. Hand wash or dry clean only. Water resistant. Not suitable for heavy rain. Iron on low heat on reverse side only.",
                            Name = "Navy Bomber Jacket",
                            OnSale = true,
                            Price = 10m,
                            ShortDescription = "Classic bomber jacket with a modern slim fit."
                        },
                        new
                        {
                            Id = 13,
                            BrandId = 3,
                            CategoryId = 3,
                            LongDescription = "65% polyester, 35% cotton. Machine wash at 30°C. Water resistant coating. Suitable for light rain. Do not tumble dry. Iron on low heat.",
                            Name = "Khaki Field Jacket",
                            OnSale = false,
                            Price = 11m,
                            ShortDescription = "Rugged field jacket with multiple pockets for outdoor adventures."
                        },
                        new
                        {
                            Id = 14,
                            BrandId = 4,
                            CategoryId = 3,
                            LongDescription = "60% wool, 40% polyester. Dry clean only. Not water resistant — avoid heavy rain. Iron on low heat with a damp cloth. Provides excellent insulation in cold weather.",
                            Name = "Wool Blend Overcoat",
                            OnSale = false,
                            Price = 200m,
                            ShortDescription = "Elegant overcoat perfect for a smart winter look."
                        },
                        new
                        {
                            Id = 15,
                            BrandId = 3,
                            CategoryId = 3,
                            LongDescription = "100% recycled polyester. Machine wash at 30°C. Highly wind resistant and water repellent. Packable into its own pocket. Great for hiking and running.",
                            Name = "Windbreaker Jacket",
                            OnSale = false,
                            Price = 85m,
                            ShortDescription = "Lightweight windbreaker ideal for outdoor activities."
                        },
                        new
                        {
                            Id = 16,
                            BrandId = 3,
                            CategoryId = 4,
                            LongDescription = "Upper: 100% leather. Sole: rubber. Wipe clean with a damp cloth. Use leather conditioner to maintain quality. Not suitable for heavy rain or wet conditions.",
                            Name = "White Leather Sneakers",
                            OnSale = false,
                            Price = 90m,
                            ShortDescription = "Clean white leather sneakers that go with almost anything."
                        },
                        new
                        {
                            Id = 17,
                            BrandId = 3,
                            CategoryId = 4,
                            LongDescription = "Mesh upper for breathability. Rubber outsole with grip pattern for various surfaces. Machine washable at 30°C in a laundry bag. Remove insoles before washing. Not waterproof.",
                            Name = "Black Running Shoes",
                            OnSale = false,
                            Price = 120m,
                            ShortDescription = "Lightweight running shoes with excellent cushioning."
                        },
                        new
                        {
                            Id = 18,
                            BrandId = 4,
                            CategoryId = 4,
                            LongDescription = "Upper: genuine leather. Sole: rubber. Clean with a damp cloth and leather conditioner. Water resistant but avoid prolonged exposure to rain. Polish regularly to maintain finish.",
                            Name = "Brown Chelsea Boots",
                            OnSale = false,
                            Price = 150m,
                            ShortDescription = "Classic Chelsea boots that elevate any outfit."
                        },
                        new
                        {
                            Id = 19,
                            BrandId = 2,
                            CategoryId = 4,
                            LongDescription = "Canvas upper, rubber sole. Machine wash at 30°C in a laundry bag. Air dry only, do not tumble dry. Lightweight and flexible for all-day comfort.",
                            Name = "Grey Slip-On Sneakers",
                            OnSale = false,
                            Price = 70m,
                            ShortDescription = "Easy slip-on sneakers for effortless everyday wear."
                        },
                        new
                        {
                            Id = 20,
                            BrandId = 3,
                            CategoryId = 4,
                            LongDescription = "100% cotton canvas upper, rubber sole. Machine wash at 30°C. Air dry only. Not water resistant. Available in multiple colorways.",
                            Name = "High-Top Canvas Sneakers",
                            OnSale = false,
                            Price = 70m,
                            ShortDescription = "Iconic high-top sneakers with a streetwear edge."
                        });
                });

            modelBuilder.Entity("Entities.Shipping", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<decimal>("Price")
                        .HasColumnType("Money");

                    b.HasKey("Id");

                    b.ToTable("Shippings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Postnord",
                            Price = 4m
                        },
                        new
                        {
                            Id = 2,
                            Name = "Bring",
                            Price = 2m
                        });
                });

            modelBuilder.Entity("Entities.AddressCustomer", b =>
                {
                    b.HasOne("Entities.Address", "Adress")
                        .WithMany("Customers")
                        .HasForeignKey("AddressId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entities.Customer", "Customer")
                        .WithMany("Addresses")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Adress");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("Entities.Order", b =>
                {
                    b.HasOne("Entities.Customer", "Customer")
                        .WithMany("Orders")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entities.Payment", "Payment")
                        .WithMany("Orders")
                        .HasForeignKey("PaymentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entities.Shipping", "Shipping")
                        .WithMany("Orders")
                        .HasForeignKey("ShippingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Payment");

                    b.Navigation("Shipping");
                });

            modelBuilder.Entity("Entities.OrderProduct", b =>
                {
                    b.HasOne("Entities.Order", "Order")
                        .WithMany("OrderProducts")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entities.Product", "Product")
                        .WithMany("OrderProducts")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Entities.Product", b =>
                {
                    b.HasOne("Entities.Brand", "Brand")
                        .WithMany("Products")
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entities.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Brand");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Entities.Address", b =>
                {
                    b.Navigation("Customers");
                });

            modelBuilder.Entity("Entities.Brand", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("Entities.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("Entities.Customer", b =>
                {
                    b.Navigation("Addresses");

                    b.Navigation("Orders");
                });

            modelBuilder.Entity("Entities.Order", b =>
                {
                    b.Navigation("OrderProducts");
                });

            modelBuilder.Entity("Entities.Payment", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("Entities.Product", b =>
                {
                    b.Navigation("OrderProducts");
                });

            modelBuilder.Entity("Entities.Shipping", b =>
                {
                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
